fix: improve error message when mirrored tasks depend on stage and prod (#970)
example:
Exception: Cannot run task with fetches from stage and production clusters. translations-build-vocab-ru-en depends on the following task/clusters: defaultdict(<class 'set'>, {'stage': {'translations-toolchain-marian', 'translations-corpus-merge-parallel-ru-en'}, 'prod': {'YtV46H_fTEeoeAP-BsYE7w', 'DBWfYHC5ShGSVHrJ6kGBnA', 'KNljjLQGQ26TvBTw2mbihQ', 'YzcouzkVRAWLLJtHGM6tfQ'}})

(It's unfortunate that we only get task ids for prod; but we don't have a handle on those tasks, so it's the best we can do without looking up the task names, which is not worthwhile for an error message IMO.)