fix: include startup tests in firefoxci-artifact include-attrs (#462)
Without it, we clone the startup-test tasks but not their docker images and get errors such as:
```
Exception: Task 'gecko-startup-test-linux64-aarch64' lists a dependency that does not exist: 'firefoxci-artifact-gecko-F0RmCHwIR2qU-CvV3sOkzA'
```

Oversight from #456